kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: local-storage
